version: "3"
services:
  redis:
    image: redis:alpine
    container_name: docker_redis
    restart: always
    #volumes:
    #  - ./data/datadir:/data
    #  - ./data/conf/redis.conf:/usr/local/etc/redis/redis.conf
    #  - ./data/logs:/logs
    #command: redis-server /etc/redis/redis.conf # 覆盖容器启动后默认执行的命令
  mysqldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lwstar
      MYSQL_DATABASE: test
    ports:
      - "13306:3306"
  zero_learn_v1:
    build:
      context: ./
    #    ports:
    #      - "9999:8888"
    restart: always
    depends_on:
      - redis
      - mysqldb
#    healthcheck:
#      test: ["CMD", "curl"， "-f", "http://127.0.0.1:8888/greet/checking"]
#      interval: 30s
#      timeout: 10s
#      retries: 6
  lb:
    image: dockercloud/haproxy
    links:
      - zero_learn_v1
    ports:
      - "8888:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock